<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputGLUXZipUpdateInput</name>
   <tag></tag>
   <elementGuidId>3eb443cf-bb3f-4dac-9c64-82b91a728395</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='GLUXZipUpdateInput']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#GLUXZipUpdateInput</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>856d02b9-79a4-4726-a3ba-c31ff126e6d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>GLUX_Full_Width a-declarative</value>
      <webElementGuid>f0e43b4a-5781-42e0-a374-01c2bad931c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4dcfd6e0-4cdb-4817-b7ef-5af1916b8e67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>a93d2dca-744f-4481-bfc3-04dca963858b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>500058</value>
      <webElementGuid>15279df0-301b-4729-b39e-725145658152</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>GLUXZipUpdateInput</value>
      <webElementGuid>c58a13df-53a4-46a6-85d7-e18281e0a726</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>or enter an Indian pincode</value>
      <webElementGuid>f0f83666-3863-4b8a-aa87-942a6aa5d983</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action</name>
      <type>Main</type>
      <value>GLUXPostalInputAction</value>
      <webElementGuid>ea60b4e9-7b76-4093-919f-41f9b26bee15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GLUXZipUpdateInput&quot;)</value>
      <webElementGuid>2433b41a-d436-4cc8-87d0-5f9f7684e70f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='GLUXZipUpdateInput']</value>
      <webElementGuid>dc769616-3864-440a-833d-a59dae86573e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='GLUXZipInputSection']/div/input</value>
      <webElementGuid>578b9b6f-a2cf-4389-bb22-eaa1d102505b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>16a1edb4-2236-4723-be83-161314ce6534</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'GLUXZipUpdateInput']</value>
      <webElementGuid>888484b9-707c-40fd-865f-6579ea3738f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
